version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - python -m pytest
      - echo "Building Docker image..."
      - docker build -t weather-app .
  post_build:
    commands:
      - echo "Build completed"

